"""
Generate deterministic Playwright Page Object classes (.ts) from an inventory.

No LLM: locators are copied verbatim from the inventory's recommended_selector
(only `page.` -> `this.page.`), so the hard-won correctness (e.g. `Scan` needing
exact:true) is preserved. Locators are exposed as readonly properties; actions and
a few anchor assertions are methods. Output also returns an API surface used to
build the LLM spec prompt (single source of truth — prompt can't drift from code).
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional

from core.domain.ui_element import UIElement
from infrastructure.export.pom.element_bucketer import PageBucket, DASHBOARD

GENERATED_BANNER = (
    "// @generated by test_gen POM generator — DO NOT EDIT.\n"
    "// Source: inventory.json ({captured_at}). Re-run scripts/generate_ui_automation.py to refresh.\n"
)

# TS reserved words / globals to avoid as identifiers.
_RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger", "default",
    "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for",
    "function", "if", "import", "in", "instanceof", "new", "null", "return", "super",
    "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with",
    "let", "static", "yield", "await", "async", "page", "expect",
}

_ROLE_SUFFIX = {
    "button": "Button", "link": "Link", "tab": "Tab", "menuitem": "MenuItem",
    "checkbox": "Checkbox", "radio": "Radio", "switch": "Switch",
    "textbox": "Input", "searchbox": "Search", "combobox": "Select",
    "spinbutton": "Spinner", "slider": "Slider",
    "heading": "Heading", "columnheader": "Column", "tabpanel": "Panel",
    "banner": "Banner", "navigation": "Nav", "main": "Main", "region": "Region",
    "dialog": "Dialog", "alert": "Alert",
}

_INTERACTIVE = {"button", "link", "tab", "menuitem", "checkbox", "radio", "switch"}
_FILLABLE = {"textbox", "searchbox", "combobox", "spinbutton"}

# Roles we emit as page-object members. Landmarks (navigation/main/banner/region)
# are structural and our accessible-name approximation for them is unreliable, so
# they are excluded — they aren't useful targets for specs anyway.
_MEMBER_ROLES = _INTERACTIVE | _FILLABLE | {"heading", "columnheader", "tab", "tabpanel"}


def _cap_first(s: str) -> str:
    """Capitalize the first char WITHOUT lowercasing the rest (preserves camelCase)."""
    return s[:1].upper() + s[1:] if s else s


def _has_alnum(s: str) -> bool:
    return any(c.isalnum() for c in s)


def _camel(s: str) -> str:
    """camelCase identifier base from arbitrary text."""
    parts = []
    word = ""
    for ch in s:
        if ch.isalnum():
            word += ch
        elif word:
            parts.append(word)
            word = ""
    if word:
        parts.append(word)
    if not parts:
        return ""
    first = parts[0].lower()
    rest = [p[:1].upper() + p[1:] for p in parts[1:]]
    out = first + "".join(rest)
    # leading digit guard
    if out and out[0].isdigit():
        out = "n" + out
    return out


def _pascal(s: str) -> str:
    c = _camel(s)
    return c[:1].upper() + c[1:] if c else c


def _this_selector(recommended: str) -> str:
    """Rewrite the inventory's `page....` selector to `this.page....`."""
    if recommended.startswith("page."):
        return "this." + recommended
    return recommended


@dataclass
class Member:
    locator_name: str          # e.g. "scanButton"
    selector: str              # e.g. "this.page.getByRole('button', { name: 'Scan', exact: true })"
    role: str
    accessible_name: str


@dataclass
class PageObjectAPI:
    """The public surface of a generated page object (for the spec prompt)."""
    class_name: str            # e.g. "ScannerPage"
    fixture_name: str          # e.g. "scanner"
    locators: List[str] = field(default_factory=list)   # property names
    actions: List[str] = field(default_factory=list)    # method signatures
    assertions: List[str] = field(default_factory=list) # method signatures


@dataclass
class GeneratedPageObject:
    class_name: str
    file_name: str             # e.g. "ScannerPage.ts"
    code: str
    api: PageObjectAPI


def _class_name(page_name: str) -> str:
    return _pascal(page_name) + "Page"


def _fixture_name(page_name: str) -> str:
    return _camel(page_name)


def _unique(name: str, used: set, role: str) -> str:
    """Ensure identifier uniqueness within a class; suffix by role then number."""
    if name in _RESERVED:
        name = name + _ROLE_SUFFIX.get(role, "El")
    candidate = name
    if candidate in used:
        candidate = name + _ROLE_SUFFIX.get(role, "El")
    i = 2
    while candidate in used:
        candidate = f"{name}{i}"
        i += 1
    used.add(candidate)
    return candidate


def _build_members(elements: List[UIElement]) -> List[Member]:
    used = set()
    members: List[Member] = []
    for e in elements:
        if not e.recommended_selector:
            continue
        if e.role not in _MEMBER_ROLES:
            continue
        base = _camel(e.accessible_name) or _camel(e.role)
        loc_name = _unique(base + _ROLE_SUFFIX.get(e.role, ""), used, e.role)
        members.append(Member(
            locator_name=loc_name,
            selector=_this_selector(e.recommended_selector),
            role=e.role,
            accessible_name=e.accessible_name,
        ))
    return members


def generate_page_object(bucket: PageBucket, captured_at: str = "") -> GeneratedPageObject:
    """Generate one page object .ts file + its API surface from a bucket."""
    class_name = _class_name(bucket.name)
    members = _build_members(bucket.elements)
    is_dashboard = bucket.name == DASHBOARD

    api = PageObjectAPI(class_name=class_name, fixture_name=_fixture_name(bucket.name))
    lines: List[str] = []
    lines.append(GENERATED_BANNER.format(captured_at=captured_at or "unknown"))
    lines.append("import { Page, Locator, expect } from '@playwright/test';")
    lines.append("import { BasePage } from './BasePage';")
    lines.append("")
    lines.append(f"export class {class_name} extends BasePage {{")

    # Locator properties
    for m in members:
        lines.append(f"  readonly {m.locator_name}: Locator;")
        api.locators.append(m.locator_name)
    lines.append("")

    # Constructor
    lines.append("  constructor(page: Page) {")
    lines.append("    super(page);")
    for m in members:
        lines.append(f"    this.{m.locator_name} = {m.selector};")
    lines.append("  }")

    method_names: set = set()

    # Dashboard-specific navigation + entry
    if is_dashboard:
        lines.append("")
        lines.append("  async goto(): Promise<void> {")
        lines.append("    await this.page.goto('/');")
        lines.append("  }")
        api.actions.append("goto(): Promise<void>")
        # open<Tab>() for each nav target
        nav_member = {m.accessible_name: m.locator_name for m in members}
        for target in bucket.nav_targets:
            method = "open" + _pascal(target)
            loc = nav_member.get(target)
            if not loc or method in method_names:
                continue
            method_names.add(method)
            lines.append("")
            lines.append(f"  async {method}(): Promise<void> {{")
            lines.append(f"    await this.{loc}.click();")
            lines.append("  }")
            api.actions.append(f"{method}(): Promise<void>")

    # Action methods (skip nav buttons already covered by open* on Dashboard)
    nav_locs = set()
    if is_dashboard:
        nav_member = {m.accessible_name: m.locator_name for m in members}
        nav_locs = {nav_member.get(t) for t in bucket.nav_targets}
    for m in members:
        if m.locator_name in nav_locs:
            continue
        if m.role in _INTERACTIVE:
            method = "click" + _pascal(m.accessible_name or m.role)
            method = _dedupe_method(method, method_names)
            lines.append("")
            lines.append(f"  async {method}(): Promise<void> {{")
            lines.append(f"    await this.{m.locator_name}.click();")
            lines.append("  }")
            api.actions.append(f"{method}(): Promise<void>")
        elif m.role in _FILLABLE:
            method = "fill" + _pascal(m.accessible_name or m.role)
            method = _dedupe_method(method, method_names)
            lines.append("")
            lines.append(f"  async {method}(value: string): Promise<void> {{")
            lines.append(f"    await this.{m.locator_name}.fill(value);")
            lines.append("  }")
            api.actions.append(f"{method}(value: string): Promise<void>")

    # Anchor assertions: headings + the first meaningful columnheader (table anchor).
    first_column_done = False
    for m in members:
        make = False
        if m.role == "heading":
            make = True
        elif m.role == "columnheader" and not first_column_done and _has_alnum(m.accessible_name):
            make = True
            first_column_done = True
        if not make:
            continue
        method = "expect" + _cap_first(m.locator_name) + "Visible"
        method = _dedupe_method(method, method_names)
        lines.append("")
        lines.append(f"  async {method}(): Promise<void> {{")
        lines.append(f"    await expect(this.{m.locator_name}).toBeVisible();")
        lines.append("  }")
        api.assertions.append(f"{method}(): Promise<void>")

    # Dashboard convenience: expectLoaded() asserts app title
    if is_dashboard:
        title = next((m for m in members if m.role == "heading"), None)
        if title:
            lines.append("")
            lines.append("  async expectLoaded(): Promise<void> {")
            lines.append(f"    await expect(this.{title.locator_name}).toBeVisible();")
            lines.append("  }")
            api.assertions.append("expectLoaded(): Promise<void>")

    lines.append("}")
    code = "\n".join(lines) + "\n"
    return GeneratedPageObject(
        class_name=class_name,
        file_name=f"{class_name}.ts",
        code=code,
        api=api,
    )


def _dedupe_method(name: str, used: set) -> str:
    candidate = name
    i = 2
    while candidate in used:
        candidate = f"{name}{i}"
        i += 1
    used.add(candidate)
    return candidate


def generate_all(buckets: List[PageBucket], captured_at: str = "") -> List[GeneratedPageObject]:
    return [generate_page_object(b, captured_at) for b in buckets]
