"""
Scaffold + maintain a standalone Playwright POM project.

Responsibilities:
- ensure_scaffold(): write hand-owned scaffold files ONCE (skip if present) —
  package.json, playwright.config.ts, tsconfig.json, .gitignore, README.md,
  pages/BasePage.ts; copy API mock fixtures into fixtures/mocks/ (skip if present).
- write_page_objects(): overwrite the @generated page object .ts files (refuses to
  clobber a pages/*.ts that a user has converted to hand-owned by removing the banner).
- write_fixtures(): regenerate fixtures/test-fixtures.ts (derived from the page objects
  + api mocks, so it always stays in sync).
- write_spec(): write a generated spec into tests/.
"""
import os
import shutil
from typing import List, Dict, Optional

from infrastructure.export.pom.page_object_generator import (
    GeneratedPageObject, PageObjectAPI, GENERATED_BANNER,
)

HAND_OWNED_BANNER = "// @hand-owned — safe to edit; not regenerated by test_gen.\n"
_GEN_MARKER = "// @generated by test_gen POM generator"


class ProjectScaffolder:
    def __init__(self, project_path: str, app_name: str = "Application"):
        self.root = project_path
        self.app_name = app_name
        self.pages_dir = os.path.join(self.root, "pages")
        self.fixtures_dir = os.path.join(self.root, "fixtures")
        self.mocks_dir = os.path.join(self.fixtures_dir, "mocks")
        self.tests_dir = os.path.join(self.root, "tests")

    # --- scaffold (once) ---
    def ensure_scaffold(self, mock_body_files: Optional[List[str]] = None) -> List[str]:
        """Create scaffold files if missing. Returns list of created paths."""
        for d in (self.root, self.pages_dir, self.fixtures_dir, self.mocks_dir, self.tests_dir):
            os.makedirs(d, exist_ok=True)

        created = []
        created += self._write_if_missing("package.json", self._package_json())
        created += self._write_if_missing("playwright.config.ts", self._playwright_config())
        created += self._write_if_missing("tsconfig.json", self._tsconfig())
        created += self._write_if_missing(".gitignore", self._gitignore())
        created += self._write_if_missing("README.md", self._readme())
        created += self._write_if_missing(os.path.join("pages", "BasePage.ts"), self._base_page())

        # Copy mock fixtures (skip if already present, to respect hand edits)
        for src in (mock_body_files or []):
            dst = os.path.join(self.mocks_dir, os.path.basename(src))
            if not os.path.exists(dst) and os.path.exists(src):
                shutil.copyfile(src, dst)
                created.append(dst)
        return created

    # --- page objects (regenerated) ---
    def write_page_objects(self, generated: List[GeneratedPageObject]) -> None:
        os.makedirs(self.pages_dir, exist_ok=True)
        for g in generated:
            path = os.path.join(self.pages_dir, g.file_name)
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    head = f.read(200)
                if _GEN_MARKER not in head:
                    print(f"  Skipping {g.file_name}: file exists without @generated banner "
                          f"(treated as hand-owned)")
                    continue
            with open(path, "w", encoding="utf-8") as f:
                f.write(g.code)

    # --- fixtures (regenerated, kept in sync with page objects) ---
    def write_fixtures(self, apis: List[PageObjectAPI], api_mocks: List[Dict[str, str]]) -> None:
        os.makedirs(self.fixtures_dir, exist_ok=True)
        path = os.path.join(self.fixtures_dir, "test-fixtures.ts")
        with open(path, "w", encoding="utf-8") as f:
            f.write(self._fixtures(apis, api_mocks))

    # --- spec ---
    def write_spec(self, file_name: str, content: str) -> str:
        os.makedirs(self.tests_dir, exist_ok=True)
        path = os.path.join(self.tests_dir, file_name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

    # --- helpers ---
    def _write_if_missing(self, rel: str, content: str) -> List[str]:
        path = os.path.join(self.root, rel)
        if os.path.exists(path):
            return []
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return [path]

    # --- file templates ---
    def _package_json(self) -> str:
        name = "gap-trading-forecaster-ui-automation"
        return (
            "{\n"
            f'  "name": "{name}",\n'
            '  "version": "0.1.0",\n'
            '  "private": true,\n'
            '  "scripts": {\n'
            '    "test": "playwright test",\n'
            '    "report": "playwright show-report"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@playwright/test": "^1.40.0",\n'
            '    "@types/node": "^22.0.0",\n'
            '    "typescript": "^5.6.0"\n'
            "  }\n"
            "}\n"
        )

    def _playwright_config(self) -> str:
        return (
            HAND_OWNED_BANNER +
            "import { defineConfig } from '@playwright/test';\n\n"
            "export default defineConfig({\n"
            "  testDir: './tests',\n"
            "  timeout: 15000,\n"
            "  expect: { timeout: 5000 },\n"
            "  reporter: process.env.PW_JSON ? 'json' : 'list',\n"
            "  use: {\n"
            "    headless: true,\n"
            "    baseURL: process.env.BASE_URL || 'http://localhost:3000',\n"
            "    trace: 'on-first-retry',\n"
            "  },\n"
            "});\n"
        )

    def _tsconfig(self) -> str:
        return (
            "{\n"
            '  "compilerOptions": {\n'
            '    "target": "ES2021",\n'
            '    "module": "CommonJS",\n'
            '    "moduleResolution": "node",\n'
            '    "strict": true,\n'
            '    "esModuleInterop": true,\n'
            '    "skipLibCheck": true,\n'
            '    "types": ["node"]\n'
            "  },\n"
            '  "include": ["pages", "fixtures", "tests"]\n'
            "}\n"
        )

    def _gitignore(self) -> str:
        return "node_modules/\ntest-results/\nplaywright-report/\n.pwbrowsers/\n.npmcache/\n"

    def _base_page(self) -> str:
        return (
            HAND_OWNED_BANNER +
            "import { Page, Locator, expect } from '@playwright/test';\n\n"
            "/** Base class for all page objects. Hand-owned — safe to extend. */\n"
            "export class BasePage {\n"
            "  constructor(protected readonly page: Page) {}\n\n"
            "  async expectVisible(locator: Locator): Promise<void> {\n"
            "    await expect(locator).toBeVisible();\n"
            "  }\n"
            "}\n"
        )

    def _fixtures(self, apis: List[PageObjectAPI], api_mocks: List[Dict[str, str]]) -> str:
        imports = "\n".join(
            f"import {{ {a.class_name} }} from '../pages/{a.class_name}';" for a in apis
        )
        type_lines = "\n".join(f"  {a.fixture_name}: {a.class_name};" for a in apis)
        po_fixtures = "\n".join(
            f"  {a.fixture_name}: async ({{ page }}, use) => {{ await use(new {a.class_name}(page)); }},"
            for a in apis
        )
        mock_lines = "\n".join(
            f"    await mock(page, '{m['url_glob']}', '{os.path.basename(m['body_file'])}');"
            for m in api_mocks
        )
        return (
            GENERATED_BANNER.format(captured_at="derived from page objects") +
            "import { test as base, expect, Page } from '@playwright/test';\n"
            "import * as fs from 'fs';\n"
            "import * as path from 'path';\n"
            f"{imports}\n\n"
            "const mocksDir = path.join(__dirname, 'mocks');\n"
            "function mock(page: Page, glob: string, file: string) {\n"
            "  return page.route(glob, (route) =>\n"
            "    route.fulfill({\n"
            "      contentType: 'application/json',\n"
            "      body: fs.readFileSync(path.join(mocksDir, file), 'utf-8'),\n"
            "    }));\n"
            "}\n\n"
            "type Pages = {\n"
            f"{type_lines}\n"
            "};\n\n"
            "export const test = base.extend<Pages>({\n"
            "  page: async ({ page }, use) => {\n"
            f"{mock_lines}\n"
            "    await use(page);\n"
            "  },\n"
            f"{po_fixtures}\n"
            "});\n\n"
            "export { expect };\n"
        )

    def _readme(self) -> str:
        return (
            f"# {self.app_name} — UI Automation (POM)\n\n"
            "Generated by the test_gen framework. **Page objects and specs are `@generated`** "
            "from a live UI element inventory — do not hand-edit files that carry the\n"
            "`@generated` banner; re-run the generator instead. Scaffold files "
            "(`playwright.config.ts`, `pages/BasePage.ts`, this README) are hand-owned.\n\n"
            "## Architecture\n\n"
            "```\n"
            "pages/        Page objects (BasePage hand-owned; the rest @generated, grounded locators)\n"
            "fixtures/     test-fixtures.ts (@generated: injects page objects + mocks) + mocks/*.json\n"
            "tests/        @generated specs that call page-object methods (never raw selectors)\n"
            "```\n\n"
            "## Install (sandbox-friendly)\n\n"
            "```bash\n"
            "npm install --cache /tmp/npm-cache\n"
            "PLAYWRIGHT_BROWSERS_PATH=$PWD/.pwbrowsers npx playwright install chromium\n"
            "```\n\n"
            "## Run\n\n"
            "The frontend must be running (e.g. `pnpm dev` in the app's `web/` dir). The backend is\n"
            "mocked at the network layer from `fixtures/mocks/*.json`, so it need not run.\n\n"
            "```bash\n"
            "# point BASE_URL at the dev server (3000, or 3001 if 3000 is taken)\n"
            "BASE_URL=http://localhost:3001 PLAYWRIGHT_BROWSERS_PATH=$PWD/.pwbrowsers npx playwright test\n"
            "```\n"
        )
