#!/usr/bin/env python3
"""
Project Setup Tool - Interactive helper for onboarding new projects.

Usage:
    python3 setup_project.py create    # Create new project config
    python3 setup_project.py verify    # Verify existing project config
    python3 setup_project.py list      # List all configured projects
"""
import os
import sys
from pathlib import Path


def create_project():
    """Interactive project creation wizard."""
    print("\n" + "="*60)
    print("NEW PROJECT SETUP WIZARD")
    print("="*60 + "\n")

    # Basic info
    project_id = input("Project ID (lowercase, no spaces, e.g., 'mediapedia'): ").strip().lower().replace(" ", "-")
    app_name = input("Application name (e.g., 'MediaPedia'): ").strip()
    description = input("Brief description: ").strip()

    # App type
    print("\nApp type options: desktop, web, mobile, hybrid")
    app_type = input("App type [web]: ").strip() or "web"

    # ADO info
    print("\n--- Azure DevOps Configuration ---")
    ado_org = input("ADO Organization (e.g., 'cdpinc'): ").strip()
    ado_project = input("ADO Project name: ").strip()
    area_path = input("Area Path (e.g., 'Project\\Team'): ").strip()
    assigned_to = input("Default assignee email: ").strip()

    # Platforms
    print("\nPlatforms (comma-separated, e.g., 'Chrome, Firefox, Safari')")
    platforms_input = input("Platforms [Chrome, Firefox]: ").strip() or "Chrome, Firefox"
    platforms = [p.strip() for p in platforms_input.split(",")]

    # Unavailable features
    print("\n--- Feature Constraints ---")
    print("List features that DON'T exist in your app (prevents impossible test cases)")
    print("Examples: multi-select, offline mode, batch processing")
    unavailable_input = input("Unavailable features (comma-separated, or press Enter to skip): ").strip()
    unavailable_features = [f.strip() for f in unavailable_input.split(",") if f.strip()]

    # UI surfaces
    print("\nUI Surfaces (main areas of your app)")
    print("Examples: Dashboard, Settings Page, Navigation Menu, Editor Panel")
    ui_input = input("UI Surfaces (comma-separated): ").strip()
    ui_surfaces = [s.strip() for s in ui_input.split(",") if s.strip()]

    # Generate YAML content
    yaml_content = f'''# {app_name} Project Configuration
# Generated by setup_project.py

project_id: {project_id}

application:
  name: "{app_name}"
  description: "{description}"
  type: {app_type}

  # Step templates
  prereq_template: "Pre-req: User has access to {{app_name}}"
  launch_step: "Navigate to {{app_name}}."
  launch_expected: "Application loads successfully."
  close_step: "Close/log out of {{app_name}}."

  # Features that DON'T exist (prevents generating impossible tests)
  unavailable_features:
'''
    for feature in unavailable_features:
        yaml_content += f'    - "{feature}"\n'

    if not unavailable_features:
        yaml_content += '    []  # Add features that don\'t exist in your app\n'

    yaml_content += '''
  # Map AC terminology to actual feature names
  feature_aliases: {}

  # Notes/warnings about specific features
  feature_notes: {}

  # UI surfaces
  ui_surfaces:
'''
    for surface in ui_surfaces:
        yaml_content += f'    - "{surface}"\n'

    yaml_content += '''
  # Map keywords to UI locations
  entry_point_mappings:
    settings: "Settings"
    profile: "User Profile"

  # Supported platforms
  platforms:
'''
    for platform in platforms:
        yaml_content += f'    - "{platform}"\n'

    yaml_content += f'''
ado:
  organization: "{ado_org}"
  project: "{ado_project}"
  area_path: "{area_path}"
  assigned_to: "{assigned_to}"
  default_state: "Design"
  test_suite_pattern: "{{story_id}} : {{story_name}}"
  qa_prep_pattern: null  # Set to "Story {{story_id}}: QA Prep" if using QA Prep tasks

rules:
  forbidden_words:
    - "or / OR"
    - "if available"
  first_test_id: "AC1"
  test_id_increment: 5

output_dir: "output/{project_id}"
llm_enabled: true
llm_provider: "openai"
llm_model: "gpt-4o-mini"
'''

    # Save the config
    config_dir = Path("projects/configs")
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / f"{project_id}.yaml"

    with open(config_path, 'w') as f:
        f.write(yaml_content)

    print(f"\n✅ Config saved to: {config_path}")

    # Create .env template
    env_example = f'''
# {app_name} Environment Variables
# Copy these to your .env file

ADO_PAT=your_personal_access_token_here
ADO_ORG={ado_org}
ADO_PROJECT={ado_project}
ADO_AREA_PATH={area_path}
ASSIGNED_TO={assigned_to}

# LLM Provider (choose one)
OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
'''
    print("\n--- Add to .env file ---")
    print(env_example)

    print("\n--- Next Steps ---")
    print(f"1. Add the above environment variables to your .env file")
    print(f"2. Test with: python3 workflows.py --project {project_id} generate --story-id XXXXX --dry-run")
    print(f"3. Review generated tests and adjust config as needed")


def verify_project():
    """Verify an existing project configuration."""
    print("\n--- Existing Project Configs ---")
    config_dir = Path("projects/configs")
    configs = list(config_dir.glob("*.yaml"))

    if not configs:
        print("No project configs found in projects/configs/")
        return

    for i, config in enumerate(configs, 1):
        print(f"  {i}. {config.stem}")

    choice = input("\nEnter project ID to verify (or number): ").strip()

    # Handle number input
    if choice.isdigit():
        idx = int(choice) - 1
        if 0 <= idx < len(configs):
            config_path = configs[idx]
        else:
            print("Invalid selection")
            return
    else:
        config_path = config_dir / f"{choice}.yaml"

    if not config_path.exists():
        print(f"Config not found: {config_path}")
        return

    # Try to load and verify
    try:
        from projects.project_config import ProjectConfig
        config = ProjectConfig.load_from_yaml(str(config_path))
        print(f"\n✅ Config loaded successfully!")
        print(f"   Project ID: {config.project_id}")
        print(f"   App Name: {config.application.name}")
        print(f"   ADO Project: {config.ado.project}")
        print(f"   Platforms: {', '.join(config.application.supported_platforms)}")
        print(f"   Unavailable Features: {len(config.application.unavailable_features)}")

        if config.application.unavailable_features:
            for f in config.application.unavailable_features[:5]:
                print(f"      - {f}")

        # Test ADO connection
        test_ado = input("\nTest ADO connection? [y/N]: ").strip().lower()
        if test_ado == 'y':
            from ado.ado_client import ADOClient
            try:
                client = ADOClient(config.ado)
                print("✅ ADO connection successful!")
            except Exception as e:
                print(f"❌ ADO connection failed: {e}")

    except Exception as e:
        print(f"❌ Error loading config: {e}")


def list_projects():
    """List all configured projects."""
    config_dir = Path("projects/configs")
    configs = list(config_dir.glob("*.yaml"))

    print("\n--- Configured Projects ---")
    if not configs:
        print("No project configs found")
        return

    for config in sorted(configs):
        print(f"  • {config.stem}")

    print(f"\nTotal: {len(configs)} projects")
    print(f"Location: {config_dir.absolute()}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return

    command = sys.argv[1].lower()

    if command == "create":
        create_project()
    elif command == "verify":
        verify_project()
    elif command == "list":
        list_projects()
    else:
        print(f"Unknown command: {command}")
        print(__doc__)


if __name__ == "__main__":
    main()
